from prompt_iteration.prompt import Prompt
from utils_evo import agent_collaboration, testify

import argparse
import gc
import json
import logging
import openai
import os
import shutil


openai.api_key = os.getenv("OPENAI_API_KEY", openai.api_key)
logging.getLogger('requests.packages.urllib3.connectionpool').setLevel(logging.DEBUG)


def parse_optimization_points(raw_points, allowed_points):
    if ',' in raw_points:
        return [point.strip() for point in raw_points.split(',') if point.strip()]
    allowed = set(allowed_points)
    tokens = raw_points.split('_')
    points = []
    idx = 0
    while idx < len(tokens):
        match = None
        match_end = idx
        for end in range(len(tokens), idx, -1):
            candidate = '_'.join(tokens[idx:end])
            if candidate in allowed:
                match = candidate
                match_end = end
                break
        if match is None:
            raise ValueError('Cannot parse optimization point sequence: {}'.format(raw_points))
        points.append(match)
        idx = match_end
    return points


def main(args):
    dataset_name = args.dataset_name

    with open('agent_config.json', 'r') as f:
        config = json.load(f)
    candidate_agents = config['candidate_agents']
    candidate_controllers = config['candidate_controllers']
    base_roles = config.get('base_roles', ['System', 'System', 'System', 'System'])
    prompt_roles = parse_optimization_points(
        args.optimization_points, candidate_agents + candidate_controllers
    )

    for role_name in prompt_roles:
        if role_name not in (candidate_agents + candidate_controllers):
            raise ValueError('The role name {} is not in the candidate agents or controllers.'.format(role_name))

    log_dir = '../../exp_data/{}/'.format(dataset_name)
    os.makedirs(log_dir, exist_ok=True)
    logging.basicConfig(filename=os.path.join(log_dir, 'log.txt'), level=logging.INFO)

    prompt_names = '-'.join(prompt_roles)
    roles_name = '-'.join(base_roles)
    DIR_NAME_VAL = './results/math_roles_{}_pt_roles_{}_35_1106_val'.format(roles_name, prompt_names)
    DIR_NAME_TEST = './results/math_roles_{}_pt_roles_{}_35_1106_test'.format(roles_name, prompt_names)
    for directory in [DIR_NAME_VAL, DIR_NAME_TEST]:
        if os.path.exists(directory):
            shutil.rmtree(directory)
        os.makedirs(directory, exist_ok=True)

    prompt_all = Prompt(args.model_name, dataset_name)
    for iter in range(args.Iter_num):
        print('---------------Iteration {}----------------'.format(iter))
        for prompt_role in prompt_roles:
            print('---------------Init Prompts----------------')
            prompt_all.initialize(prompt_role, args.initialize_num, base_roles)
            agent_collaboration(prompt_all, prompt_role, DIR_NAME_VAL, iter, 'train')
            prompt_all.renew_prompts()

            print('---------------Feedback Mutation ----------------')
            tolerance = 0
            max_score = max(prompt_all.id2score.values())
            for t in range(args.FD_max_iter):
                prompt_pair = prompt_all.FD_parent_selection(args.FD_sample_threshold + t)
                prompt_all.FD_mutation(prompt_pair)
                agent_collaboration(prompt_all, prompt_role, DIR_NAME_VAL, iter, 'train')
                prompt_all.renew_prompts()

                if max(prompt_all.id2score.values()) - max_score < args.FD_min_improvement:
                    tolerance += 1
                max_score = max(prompt_all.id2score.values())
                if tolerance >= args.FD_tolerance_iter:
                    break
                gc.collect()

            print('---------------Testify the Optimal Prompt----------------')
            sorted_id2score = sorted(prompt_all.id2score.items(), key=lambda x: x[1], reverse=True)
            optimal_prompt_id = sorted_id2score[0][0]
            testify(prompt_all, prompt_role, optimal_prompt_id, DIR_NAME_TEST, iter)
            prompt_all.optimized_prompts[prompt_role] = prompt_all.id2prompt[optimal_prompt_id]
            gc.collect()


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    # Fun-1: ['System', 'Examples', 'Examples_cot']
    # Fun-2: "construct-role"; Str-1: "pre-rank"; Str-2: "rank"; Str-3: "structure"
    parser.add_argument('--optimization_points', type=str, default='System_rank',
                        help='sequence of optimization points, separated by _')
    parser.add_argument('--initialize_num', type=int, default=3,
                        help='number of initial prompts generated by the Semantic Initializer')
    parser.add_argument('--dataset_name', type=str, default='competition_math', help='dataset name')
    parser.add_argument('--model_name', type=str, default='gpt-3.5-turbo-1106', help='model name')
    parser.add_argument('--FD_max_iter', type=int, default=3,
                        help='Maximal steps for the contrasting optimization steps')
    parser.add_argument('--FD_min_improvement', type=float, default=0.1,
                        help='Minimal improvement threshold for the contrasting optimization steps')
    parser.add_argument('--FD_tolerance_iter', type=int, default=2,
                        help='Tolerance steps without minimal improvement for the contrasting optimization steps')
    parser.add_argument('--FD_sample_threshold', type=int, default=1,
                        help='Sampling threshold for the contrasting optimization steps')
    parser.add_argument('--Iter_num', type=int, default=1,
                        help='number of iterations for joint optimization of multiple points')

    main(parser.parse_args())
