from prompt_iteration.prompt import Prompt
from utils_evo import agent_collaboration, testify

import os
import argparse
from utils import *
import logging
import gc
import json
import shutil


openai.api_key = os.getenv("OPENAI_API_KEY", openai.api_key)

def main(args):

    prompt_roles = args.optimization_points.split('_')
    dataset_name = args.dataset_name

    initialize_num = args.initialize_num
    evol_model = args.model_name
    FD_max_iter = args.FD_max_iter
    FD_min_improvement = args.FD_min_improvement
    FD_tolerance_iter = args.FD_tolerance_iter
    FD_sample_threshold = args.FD_sample_threshold
    Iter_num = args.Iter_num

    with open('agent_config.json', 'r') as f:
        config = json.load(f)
    candidate_agents = config['candidate_agents']
    candidate_controllers = config['candidate_controllers']

    for role_name in prompt_roles:
        if role_name not in (candidate_agents + candidate_controllers):
            raise ValueError('The role name {} is not in the candidate agents or controllers.'.format(role_name))

    # specify the log file path
    log_dir = '../../exp_data/{}/'.format(dataset_name)
    os.makedirs(log_dir, exist_ok=True)
    log_file = os.path.join(log_dir, 'log.txt')
    logging.basicConfig(filename=log_file, level=logging.INFO)

    prompt_names = '-'.join(prompt_roles)
    DIR_NAME_VAL='./results/code_human_eval_{}_35_1106_val'.format(prompt_names)
    DIR_NAME_TEST='./results/code_human_eval_{}_35_1106_test'.format(prompt_names)
    # delete these two directories if they exist
    if os.path.exists(DIR_NAME_VAL):
        shutil.rmtree(DIR_NAME_VAL)
    if os.path.exists(DIR_NAME_TEST):
        shutil.rmtree(DIR_NAME_TEST)

    for iter in range(Iter_num):
        print('---------------Iteration {}----------------'.format(iter))
        prompt_all = Prompt(evol_model, dataset_name)
        # Run the prompt iteration process
        for prompt_role in prompt_roles:

            print('---------------Init Prompts----------------')
            prompt_all.initialize(prompt_role, initialize_num)
            agent_collaboration(prompt_all, prompt_role, DIR_NAME_VAL, iter)
            prompt_all.renew_prompts()

            print('---------------Feedback Mutation ----------------')
            tolerance = 0
            max_score = max(prompt_all.id2score.values())
            for t in range(FD_max_iter):
                # get two prompt ids, the first one is randomly choosen from the first score_threshold prompts with highest scores, the second one is randomly choosen from the first score_threshold prompts with the lowest score_threshold scores. The information is stored in the prompt.id2score dictionary
                prompt_pair = prompt_all.FD_parent_selection(FD_sample_threshold + t)  #  + t
                prompt_all.FD_mutation(prompt_pair)
                agent_collaboration(prompt_all, prompt_role, DIR_NAME_VAL, iter)
                prompt_all.renew_prompts()

                if max(prompt_all.id2score.values()) - max_score < FD_min_improvement:
                    tolerance += 1
                max_score = max(prompt_all.id2score.values())
                if tolerance >= FD_tolerance_iter:
                    break
                gc.collect()

            print('---------------Testify the Optimal Prompt----------------')
            # get the optimal prompt id
            sorted_id2score = sorted(prompt_all.id2score.items(), key=lambda x: x[1], reverse=True)
            optimal_prompt_id = sorted_id2score[0][0]

            testify(prompt_all, prompt_role, optimal_prompt_id, DIR_NAME_TEST, iter)

            prompt_all.optimized_prompts[prompt_role] = [prompt_all.role_names[optimal_prompt_id], prompt_all.id2prompt[optimal_prompt_id]]
            gc.collect()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    # Fun-1: ['PythonAssistant', 'AlgorithmDeveloper', 'ComputerScientist', 'Programmer', 'Passer', 'Tester', 'Reflector']
    # Fun-2: "construct-role"; Str-1: "pre-rank"; Str-2: "rank"; Str-3: "structure"
    parser.add_argument('--optimization_points', type=str, default='ComputerScientist_rank', help='sequence of optimization points, separated by _')

    parser.add_argument('--initialize_num', type=int, default=3, help='number of initial prompts generated by the Semantic Initializer')
    parser.add_argument('--dataset_name', type=str, default='human_eval', help='dataset name')
    parser.add_argument('--model_name', type=str, default='gpt-3.5-turbo-1106', help='model name')

    parser.add_argument('--FD_max_iter', type=int, default=3, help='Maximal steps for the contrasting optimization steps')
    parser.add_argument('--FD_min_improvement', type=float, default=0.01, help='Minimal improvement threshold for the contrasting optimization steps')
    parser.add_argument('--FD_tolerance_iter', type=int, default=2, help='Tolerance steps without minial improvement for the contrasting optimization steps')
    parser.add_argument('--FD_sample_threshold', type=int, default=1, help='Sampling threshold for the contrasting optimization steps')

    parser.add_argument('--Iter_num', type=int, default=1, help='number of iterations for joint optimization of multipe points')

    args = parser.parse_args()
    main(args)
